#!/usr/bin/env node
/**
 * Regenerates server/src/lib/golden-scenarios.json — the reference figures the
 * engine must keep reproducing.
 *
 * These are a change detector, not a proof of correctness: if a formula or a
 * preset moves, the numbers move and the test fails, forcing whoever changed it
 * to look at the impact and update the file on purpose. That is precisely what
 * was missing when the MCP and the web app drifted 7 ROI points apart.
 *
 *   node scripts/generate-goldens.mjs
 */

import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { build } from 'esbuild';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const LIB = join(ROOT, 'server/src/lib');

// The engine is TypeScript; bundle it for Node the same way the app's own
// tooling does, so the goldens come from the real code and not a reimplementation.
const tmp = mkdtempSync(join(tmpdir(), 'roi-goldens-'));
const bundle = join(tmp, 'engine.mjs');
await build({
  stdin: {
    contents: `
      export { calculateROI } from ${JSON.stringify(join(LIB, 'calculations.ts').replace(/\\/g, '/'))};
      export { DEFAULT_INPUTS, PRESETS } from ${JSON.stringify(join(LIB, 'constants.ts').replace(/\\/g, '/'))};
    `,
    resolveDir: LIB,
    loader: 'ts',
  },
  bundle: true,
  format: 'esm',
  platform: 'node',
  outfile: bundle,
  logLevel: 'silent',
});

const { calculateROI, DEFAULT_INPUTS, PRESETS } = await import(pathToFileURL(bundle).href);
rmSync(tmp, { recursive: true, force: true });

const round = (v) => (typeof v === 'number' ? Math.round(v * 1e6) / 1e6 : v);

/** Extra cases beyond the presets, covering the paths presets never exercise. */
const EXTRA_CASES = {
  'per-call flat rate': {
    ...DEFAULT_INPUTS,
    primaryModel: {
      ...DEFAULT_INPUTS.primaryModel,
      useCallPricing: true,
      costPerCall: 0.02,
      avgInputTokensPerUnit: 999_999, // must be ignored
    },
    routingSimplePercent: 100,
  },
  'batch on a model with published rates': {
    ...DEFAULT_INPUTS,
    ...PRESETS.meetingSummary,
    batchProcessing: true,
  },
  'batch on a model without published rates': {
    ...DEFAULT_INPUTS,
    primaryModel: {
      ...DEFAULT_INPUTS.primaryModel,
      batchInputPricePer1M: undefined,
      batchOutputPricePer1M: undefined,
    },
    batchProcessing: true,
  },
  'routing split 60/40': {
    ...DEFAULT_INPUTS,
    routingSimplePercent: 60,
  },
};

const scenarios = {};
for (const [name, inputs] of Object.entries({
  ...Object.fromEntries(
    Object.keys(PRESETS).map((key) => [`preset:${key}`, { ...DEFAULT_INPUTS, ...PRESETS[key] }]),
  ),
  ...EXTRA_CASES,
})) {
  const r = calculateROI(inputs);
  scenarios[name] = {
    layer1CostPerUnit: round(r.layer1CostPerUnit),
    layer2CostPerUnit: round(r.layer2CostPerUnit),
    totalCostPerUnit: round(r.totalCostPerUnit),
    grossValuePerUnit: round(r.grossValuePerUnit),
    totalMonthlyValue: round(r.totalMonthlyValue),
    totalMonthlyCost: round(r.totalMonthlyCost),
    netMonthlyBenefit: round(r.netMonthlyBenefit),
    roiPercentage: round(r.roiPercentage),
    paybackMonths: r.paybackMonths,
    breakEvenVolume: r.breakEvenVolume,
  };
}

const out = join(LIB, 'golden-scenarios.json');
writeFileSync(
  out,
  JSON.stringify(
    {
      _comment:
        'Generated by scripts/generate-goldens.mjs. Regenerate deliberately when a ' +
        'formula or preset changes, and review the diff — it is the blast radius.',
      scenarios,
    },
    null,
    2,
  ) + '\n',
);
console.log(`Wrote ${Object.keys(scenarios).length} scenarios to ${out}`);
